---
abstract: 'set X11 wallpaper using best available helper program'
author:
  - 'Richard Harris <RJH@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: X11-Wallpaper
requires:
  Carp: 0
  Exporter: 0
  File::Which: 0
  IPC::System::Simple: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/richardjharris/X11-Wallpaper/issues
  repository: git://github.com/richardjharris/X11-Wallpaper.git
version: 0.1
